version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "build"
      include: "scope"
    # This strategy is fine in this early stage
    versioning-strategy: increase-if-necessary
